### ISSUE TITLE
Embedded skin causing crash in PLI

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/AutoBouquetsMaker#135]
Flash PLi Dev 17/1/2020. No restores. Install ABM. 
Default/Stock/standard/OoB skin will be Full Night HD. Rename `skin_plugins.xml` to `skin_plugins.xml.bak` to invoke usage of embedded skin. Restart and then go to ABM.

```
OpenPLi Enigma2 crash log

crashdate=Fri Jan 17 15:22:30 2020
compiledate=Jan 15 2020
skin=PLi-FullNightHD/skin.xml
sourcedate=2020-01-14
branch=develop
rev=69f7c01
component=Enigma2

stbmodel=gigablue
stbmodel=gbue4k
kernelcmdline=root=/dev/mmcblk0p9 rootwait rw rootflags=data=journal libata.force=1:3.0G,2:3.0G,3:3.0G coherent_poll=2M vmalloc=525m bmem=529m@491m bmem=608m@2464m
nimsockets=NIM Socket 0:
imageissue=openpli develop %h


REMOVE Peer gbue4k
REMOVE Peer gbue4k
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 77, in action
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 57, in action
  File "/usr/lib/enigma2/python/Screens/Menu.py", line 56, in okbuttonClick
  File "/usr/lib/enigma2/python/Tools/BoundFunction.py", line 9, in __call__
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/plugin.py", line 74, in main
  File "/usr/lib/enigma2/python/mytest.py", line 302, in open
    self.execBegin()
  File "/usr/lib/enigma2/python/mytest.py", line 220, in execBegin
    self.instantiateSummaryDialog(c)
  File "/usr/lib/enigma2/python/mytest.py", line 254, in instantiateSummaryDialog
    self.summary.show()
  File "/usr/lib/enigma2/python/Screens/Screen.py", line 150, in show
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/menu.py", line 204, in addWatcher
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/menu.py", line 211, in selectionChanged
  File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/menu.py", line 95, in getCurrentEntry
TypeError: 'bool' object has no attribute '__getitem__'


dmesg
```

**Comment by Huevos** [comment]
Stack trace was no help narrowing down this issue. Needed full output from a debug log.

https://github.com/OpenPLi/enigma2/commit/2547186e937f5bb95bc262b97d1230b2e9e68fab
